name: Auto Predictions

on:
  schedule:
    - cron: "0 * * * *"   # run every hour
  workflow_dispatch:       # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run autopredict.py
        run: python autopredict.py

      - name: Commit & push predictions
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add predictions_history.csv
          git commit -m "Update predictions [skip ci]" || echo "No changes to commit"
          git push
